<?php

include drupal_get_path('module', 'cassie').'/Cassie.class.php';
include drupal_get_path('module', 'cassie').'/UUID.class.php';
include drupal_get_path('module', 'cassie').'/RuleEngine.class.php';


$GLOBALS['cassie'] = new Cassie();
$GLOBALS['cassie']->connect();

$GLOBALS['rule'] = new RuleEngine();

$GLOBALS['segments'] = array();

function cassie_init(){

	if (!isset($_COOKIE["location"])){
        	$location = file_get_contents('http://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']);

	        $jsonIterator = new RecursiveIteratorIterator(
   		     	new RecursiveArrayIterator(json_decode($location, TRUE)),
        		RecursiveIteratorIterator::SELF_FIRST);

        	$arrayJson = array();

	        foreach ($jsonIterator as $key => $val) {
                	$arrayJson[] = $val;
        	}

        	$v4uuid = UUID::v4();
	        //$language = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
        	$language = "fi";
		$ip_address = $arrayJson[0];
        	$time_zone = $arrayJson[7];
	        $country = $arrayJson[2];
        	$region = $arrayJson[4];
        	$city = $arrayJson[5];
		$os = check_user_agent();
		$cookieArray = array($v4uuid, $language, $ip_address, $time_zone, $country, $region, $city, $os);

	        $cookieJson = json_encode($cookieArray, JSON_UNESCAPED_UNICODE);

		$os = check_user_agent();
        	setcookie("location", $cookieJson, time()+3600);

	        $GLOBALS['cassie']->insertUsersSegment($v4uuid, $language, $ip_address, $time_zone, $country, $region, $city, $os);

		$visits = $GLOBALS['cassie']->checkForPromotion($v4uuid);
        	$GLOBALS['segments'] = $GLOBALS['rule']->init($visits, $language);

		return $cookieArray;
	}

	$cookie = get_cookie();
        $visits = $GLOBALS['cassie']->checkForPromotion($cookie[0]);
	$GLOBALS['segments'] = $GLOBALS['rule']->init($visits, $cookie[1]);

	check_uuid();

}

function cassie_help($path, $args) {
  if ($path == 'admin/help#cassie') {
    return t('To use this module, go to the block page and turn on the membercount block.');
  }
}

function cassie_menu() {
  $items['pants'] = array(
    'title' => 'Pants',
    'page callback' => 'pants_page',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  $items['jackets'] = array(
    'title' => 'Jackets',
    'page callback' => 'jackets_page',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  $items['phones'] = array(
    'title' => 'Phones',
    'page callback' => 'phones_page',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
  );

  $items['manage'] = array(
   'title' => 'Admin UI',
   'page callback' => 'admin_page',
   'type' => MENU_CALLBACK,
   'access callback' => TRUE,
  );

  $items['pants/%'] = array(
   'page callback' => 'pants_details',
   'access callback' => TRUE,
  );

  $items['jackets/%'] = array(
   'page callback' => 'jackets_details',
   'access callback' => TRUE,
  );

  $items['phones/%'] = array(
   'page callback' => 'phones_details',
   'access callback' => TRUE,
  );


 return $items;
}


function cassie_block_info() {
  $blocks['language'] = array(
    'info' => t('language'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  $blocks['ad'] = array(
    'info' => t('ad'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function cassie_block_view($delta = '') {

   switch($delta){
     case 'ad':
	/**if (empty($_COOKIE["location"])){
		$language = "fi";
	}else{
	 	$cookie = get_cookie();
		$language = $cookie[1];
	}*/
	$advert = $GLOBALS['segments']['advertSide'];
	//echo $advert;
	$result = $GLOBALS['cassie']->selectAd($advert);
	$row = $result->first();
        $block['content'] = "<img id='adImage' src='" . $row['image_link'] . "'/>";
     return $block;

     case 'language':
	$block['subject'] = t("Language");

	$block['content'] = "<form method='POST' action=''><div id='fi'><input type='submit' id='fiFlag' class='flags' name='fi' value=''></div>".
	"<div id='ru'><input type='submit' id='ruFlag' class='flags' name='ru' value=''></div></form>";
	select_language();
     return $block;
  }

}

function select_language(){
	if (isset($_POST['fi'])) {
		$cookie = get_cookie();
		$cookieArray = array($cookie[0], "fi", $cookie[2], $cookie[3], $cookie[4], $cookie[5], $cookie[6], $cookie[7]);
		$cookieJson = json_encode($cookieArray, JSON_UNESCAPED_UNICODE);

                setcookie("location", $cookieJson, time()+3600);
		header("Refresh:0");

        }
        if (isset($_POST['ru'])) {
		$cookie = get_cookie();
                $cookieArray = array($cookie[0], "ru", $cookie[2], $cookie[3], $cookie[4], $cookie[5], $cookie[6], $cookie[7]);
                $cookieJson = json_encode($cookieArray, JSON_UNESCAPED_UNICODE);

                setcookie("location", $cookieJson, time()+3600);
		header("Refresh:0");
        }

}

function get_cookie(){
	if (isset($_COOKIE['location'])){
		$cookie = $_COOKIE['location'];
        	$cookie = stripslashes($cookie);
        	$cookieArray = json_decode($cookie, true);
		return $cookieArray;
	} else{
		return cassie_init();
	}
}


function get_products(){
	if (isset($_COOKIE['location'])){
	$cookie = get_cookie();
	}
	//echo $cookie[1];
	//$init = $GLOBALS['rule']->init($cookieArray[0], $cookieArray[1]);

	$userAgent = check_user_agent();
	//echo $userAgent;
	$address = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

	$page = substr(strrchr($address, '/'), 1);
	$test = true;
	$cookie = get_cookie();
	//$os = get_user_agent();
	$result = $GLOBALS['cassie']->getProductsByOs($page,"iPhone");
	$result2 = $GLOBALS['cassie']->getProductsByOs($page,"Android");
	$result3 = $GLOBALS['cassie']->getTest($page, "iPhone", true);

	$output = "<div>";
	$i = 0;
	$highpriority = false;
	$cookie = get_cookie();
	$visits = $GLOBALS['cassie']->checkForPromotion($cookie[0]);
	$segments = $GLOBALS['rule']->init($visits, 1);
	$highpriority = $segments['priorityHigh'];
	//echo $highpriority;
	//echo $visits;
	if ($highpriority === 1){
		foreach ($result3 as $row) {
                	$output .= "<a href='". $page . "/" . $row['product_id'] . "'><div class='productContainer'><div class='product'><img id='productImage$i' class='productImage' src='"
                 	. $row['image_link'] . "'/><p id='productName'>" . $row['product_id'] . "</p><p id='productPrice'>" . $row['price'] .
                	" &#x20ac;</p><p id='productDescription'>" . $row['description'] . "</div></div></a>";
                	$i++;
        	}
	}


        foreach ($result as $row) {
                $output .= "<a href='". $page . "/" . $row['product_id'] . "'><div class='productContainer'><div class='product'><img id='productImage$i' class='productImage' src='"
		 . $row['image_link'] . "'/><p id='productName'>" . $row['product_id'] . "</p><p id='productPrice'>" . $row['price'] .
		" &#x20ac;</p><p id='productDescription'>" . $row['description'] . "</div></div></a>";
		$i++;
        }

	foreach ($result2 as $row) {
                $output .= "<a href='". $page . "/" . $row['product_id'] . "'><div class='productContainer'><div class='product'><img id='productImage$i' class='productImage' src='"
                 . $row['image_link'] . "'/><p id='productName'>" . $row['product_id'] . "</p><p id='productPrice'>" . $row['price'] .
                " &#x20ac;</p><p id='productDescription'>" . $row['description'] . "</div></div></a>";
                $i++;
        }

        $output .= "</div>";

	return $output;

}


function check_user_agent(){
 	$userAgent = $_SERVER['HTTP_USER_AGENT'];
	$os = "";
	if (strpos($userAgent, 'Android') !== false) {
    		$os = "Android";
	}

	if(strpos($userAgent, 'Windows') !== false){
		$os = "Windows";
	}

	if (strpos($userAgent, 'iPhone') !== false){
		$os = "iPhone";
	}

	return "Android";
}

function phones_page(){
	updateCounter();
	return get_products();
}

function pants_page() {
	updateCounter();
	return get_products();
}

function jackets_page(){
	updateCounter();
	return get_products();
}

function admin_page(){
	if (user_access('administer')) {
		return "jeeeee";
	}else{
		drupal_set_title("Access denied");
		return "You are not authorized to access this page.";
	}
}

function get_product_details(){

        $address = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

        $pageUnparsed = explode("/", $address, 3);
        $pageWithSubpage = substr($pageUnparsed[2], strpos($pageUnparsed[2], "/") + 1);
        $page = explode("/", $pageWithSubpage, 2);

        $productWithSpecials = substr(strrchr($address, '/'), 1);
	$product = str_replace("%20"," ", $productWithSpecials);
	$os = "Android";

        $result = $GLOBALS['cassie']->getProductInfo($product);

        $row = $result->first();
	drupal_set_title($row['product_id']);
        $output = "<p id='productDetailPrice'>" . $row['price'] . " &#x20ac;</p><p id='productDetailDescription'>"
	. $row['description']. "</p><img id='productDetailImage' src='" . $row['image_link'] . "'><form method='POST' action=''><br><button type='submit' id='addToCart'".
	" class='cart' name='cart'>Add to cart <i class='fa fa-arrow-right fa-lg'></i><i class='fa fa-shopping-cart fa-lg'></i></button></form>";
	add_to_cart();
        return $output;
}

function check_uuid(){
	if (!isset($_SESSION['uuid'])){
		$_SESSION['uuid'] = UUID::v4();
	}
}

function add_to_cart(){
	if (isset($_POST['cart'])){

       		$address = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

        	$pageUnparsed = explode("/", $address, 3);
        	$pageWithSubpage = substr($pageUnparsed[2], strpos($pageUnparsed[2], "/") + 1);
        	$page = explode("/", $pageWithSubpage, 2);

		$cookie = get_cookie();

		$productWithSpecials = substr(strrchr($address, '/'), 1);
        	$product = str_replace("%20"," ", $productWithSpecials);
		$result = $GLOBALS['cassie']->getProductInfo($product);
		$row = $result->first();
		check_uuid();
		$GLOBALS['cassie']->cartProduct($_SESSION['uuid'], $product, $row['price'], $row['image_link']);


		if (!isset($_COOKIE['count'])){
			setcookie("count", 1, time()+3600, '/');
		}else{
			$count = $_COOKIE['count'];
			setcookie("count", $count + 1, time()+3600, '/');
		}
		header("Refresh:0");
		drupal_set_message($product . " added to cart.");
	}
}


function phones_details(){
	updateCounter();
	return get_product_details();
}

function pants_details(){
        return get_product_details();
}

function jackets_details(){
    	return get_product_details();
}

function updateCounter(){

	$address = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

        $pageWasRefreshed = isset($_SERVER['HTTP_CACHE_CONTROL']) && $_SERVER['HTTP_CACHE_CONTROL'] === 'max-age=0';

        $pageWithSpecials = substr(strrchr($address, '/'), 1);

        $page = str_replace("%20"," ", $pageWithSpecials);

	if (isset($_COOKIE['location'])){
		$cookie = get_cookie();

//        if ($pageWasRefreshed ) {
                $GLOBALS['cassie']->updateCounter($page);
		$GLOBALS['cassie']->updateVisits($cookie[0] , $page);
  //      }

	}
}


	/** stuff

	$location = file_get_contents('http://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']);

        $jsonIterator = new RecursiveIteratorIterator(
                new RecursiveArrayIterator(json_decode($location, TRUE)),
                RecursiveIteratorIterator::SELF_FIRST);

        $arrayJson = array();

        foreach ($jsonIterator as $key => $val) {
                if(is_array($val)) {
                   echo "$key:\n";
                } else {
                   $arrayJson[] = $val;
                   //echo "$val\n";

                }
        }

        //$uuids = gen_uuid();
        //$cas = new Cassandra\Uuid();
        //$uuid = $cas->__construct(j);
        $v4uuid = UUID::v4();
        $language = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
        $ip_address = $arrayJson[0];
        $time_zone = $arrayJson[7];
        $country = $arrayJson[2];
        $region = $arrayJson[4];
        $city = $arrayJson[5];

        $cookieArray = array($v4uuid, $language, $ip_address, $time_zone, $country, $region, $city);

        $cookieJson = json_encode($cookieArray, JSON_UNESCAPED_UNICODE);

        if (empty($_COOKIE["location"])) {
                setcookie("location", $cookieJson, time()+3600);
                $newCassie->insertUsers($v4uuid, $language, $ip_address, $time_zone, $country, $region, $city);
        }



	/**$cookie = $_COOKIE['location'];
        $cookie = stripslashes($cookie);
        $savedArray = json_decode($cookie, true);

        print_r($savedArray);

        */


        /**
        $result2 = $newCassie->printUser();
        $row2 = $result2->first();

        $arrayres = $row2['city'];

        print_r($arrayres);

        */

        //$result = $newCassie->getProducts($page);

        //$array = array();
        //foreach($result as $row){

        //$array[] = $row['products'];
        //}


        //foreach ($result as $row) {
        //      printf("\"%s\" \"%s\"  \n", $row['product_id'], $row['amount']);
        //}

        //$test = "<h1>dfs</h1>\n";
        //$row = $result->first();
        //$test2 = "fdsasadf";
        //$array = array();
        //$array = $row['products']->values();

        //$test = var_export($row['products'], true);


        //for($i = 0; $i < count($array); $i++){
        //      $print = $array[0] + $array[1];
        //}

        //$comma_separated = implode(", ", $array);


